import { CommandDefinition, OptionType } from './types';

export const COMMANDS: CommandDefinition[] = [
  {
    name: 'mv',
    baseCommand: 'mv',
    description: 'Move or rename files and directories.',
    args: [
        { name: 'Source', placeholder: '/path/to/source', description: 'The file or directory you want to move or rename.' },
        { name: 'Destination', placeholder: '/path/to/destination', description: 'The new location or new name for the source.' },
    ],
    options: [
      { name: 'interactive', flag: '-i, --interactive', description: 'Prompt before overwriting an existing file.', type: OptionType.FLAG },
      { name: 'force', flag: '-f, --force', description: 'Do not prompt before overwriting (overrides -i).', type: OptionType.FLAG },
      { name: 'no-clobber', flag: '-n, --no-clobber', description: 'Do not overwrite an existing file.', type: OptionType.FLAG },
      { name: 'verbose', flag: '-v, --verbose', description: 'Explain what is being done.', type: OptionType.FLAG },
      { name: 'update', flag: '-u, --update', description: 'Move only when the SOURCE file is newer than the destination file or when the destination file is missing.', type: OptionType.FLAG },
      { name: 'backup', flag: '--backup', description: 'Make a backup of each existing destination file.', type: OptionType.VALUE, placeholder: 'none, off, numbered, t, existing, simple' },
      { name: 'strip-trailing-slashes', flag: '--strip-trailing-slashes', description: 'Remove trailing slashes from each SOURCE argument.', type: OptionType.FLAG },
      { name: 'no-target-directory', flag: '-T, --no-target-directory', description: 'Treat DESTINATION as a normal file, not a directory.', type: OptionType.FLAG },
    ],
  },
  {
    name: 'cp',
    baseCommand: 'cp',
    description: 'Copy files and directories.',
    args: [
        { name: 'Source', placeholder: '/path/to/source', description: 'The file or directory you want to copy.' },
        { name: 'Destination', placeholder: '/path/to/destination', description: 'The location where the copy will be created.' },
    ],
    options: [
      { name: 'recursive', flag: '-r, -R, --recursive', description: 'Copies directories and their entire contents. Without this, `cp` will show an error if you try to copy a directory.', type: OptionType.FLAG },
      { name: 'interactive', flag: '-i, --interactive', description: 'Prompt for confirmation before overwriting any existing file.', type: OptionType.FLAG },
      { name: 'force', flag: '-f, --force', description: 'If a destination file cannot be opened for writing, `cp` will remove it and try again.', type: OptionType.FLAG },
      { name: 'verbose', flag: '-v, --verbose', description: 'Prints the name of each file as it is copied.', type: OptionType.FLAG },
      { name: 'archive', flag: '-a, --archive', description: 'Equivalent to `-dR --preserve=all`. Recursively copies and preserves all file attributes.', type: OptionType.FLAG },
      { name: 'update', flag: '-u, --update', description: 'Only copies if the source file is newer than the destination, or if the destination file does not exist.', type: OptionType.FLAG },
      { name: 'symbolic-link', flag: '-s, --symbolic-link', description: 'Create symbolic links instead of copying the files themselves.', type: OptionType.FLAG },
      { name: 'preserve', flag: '--preserve', description: 'Preserve the specified attributes (e.g., "mode,ownership,timestamps").', type: OptionType.VALUE, placeholder: 'mode,timestamps' },
      { name: 'no-clobber', flag: '-n, --no-clobber', description: 'Do not overwrite an existing file.', type: OptionType.FLAG },
      { name: 'link', flag: '-l, --link', description: 'Create hard links to files instead of copying.', type: OptionType.FLAG },
    ],
  },
  {
    name: 'tar',
    baseCommand: 'tar',
    description: 'An archiving utility to create, manage, and extract tar archives.',
    args: [
        { name: 'Archive Name', placeholder: 'archive.tar', description: 'The name of the archive file you are creating or extracting from.' },
        { name: 'Files / Directories', placeholder: 'file1.txt dir1/ ...', description: 'A space-separated list of files or directories to add to the archive.' },
    ],
    options: [
      { name: 'create', flag: '-c, --create', description: 'Create a new archive.', type: OptionType.FLAG },
      { name: 'extract', flag: '-x, --extract', description: 'Extract files from an archive.', type: OptionType.FLAG },
      { name: 'list', flag: '-t, --list', description: 'List the contents of an archive without extracting.', type: OptionType.FLAG },
      { name: 'file', flag: '-f, --file', description: 'Specifies the archive file name.', type: OptionType.FLAG },
      { name: 'verbose', flag: '-v, --verbose', description: 'Verbosely list files as they are processed.', type: OptionType.FLAG },
      { name: 'gzip', flag: '-z, --gzip', description: 'Filter the archive through gzip for compression (.tar.gz).', type: OptionType.FLAG },
      { name: 'bzip2', flag: '-j, --bzip2', description: 'Filter the archive through bzip2 for compression (.tar.bz2).', type: OptionType.FLAG },
      { name: 'xz', flag: '-J, --xz', description: 'Filter the archive through xz for high compression (.tar.xz).', type: OptionType.FLAG },
      { name: 'use-compress-program', flag: '--use-compress-program', description: 'Use a custom multi-threaded compressor (e.g., pigz).', type: OptionType.VALUE, placeholder: 'pigz' },
      { name: 'exclude', flag: '--exclude', description: 'Exclude files matching a pattern during creation.', type: OptionType.VALUE, placeholder: 'PATTERN' },
      { name: 'strip-components', flag: '--strip-components', description: 'On extraction, remove this many leading directory levels.', type: OptionType.VALUE, placeholder: 'NUMBER' },
      { name: 'remove-files', flag: '--remove-files', description: 'Delete files from the disk after adding them to the archive.', type: OptionType.FLAG },
    ],
  },
  {
    name: 'gzip',
    baseCommand: 'gzip',
    description: 'Compress or expand files.',
    args: [
        { name: 'File', placeholder: '/path/to/file', description: 'The file to compress or decompress.' },
    ],
    options: [
      { name: 'decompress', flag: '-d, --decompress', description: 'Decompress the file.', type: OptionType.FLAG },
      { name: 'force', flag: '-f, --force', description: 'Force compression or decompression.', type: OptionType.FLAG },
      { name: 'keep', flag: '-k, --keep', description: 'Keep input files during compression or decompression.', type: OptionType.FLAG },
      { name: 'list', flag: '-l, --list', description: 'List compressed file contents.', type: OptionType.FLAG },
      { name: 'verbose', flag: '-v, --verbose', description: 'Display name and percentage reduction.', type: OptionType.FLAG },
      { name: 'fast', flag: '--fast', description: 'Compress faster (less compression).', type: OptionType.FLAG },
      { name: 'best', flag: '--best', description: 'Compress better (slower).', type: OptionType.FLAG },
      { name: 'recursive', flag: '-r, --recursive', description: 'Operate recursively on directories.', type: OptionType.FLAG },
      { name: 'test', flag: '-t, --test', description: 'Test the integrity of the compressed file.', type: OptionType.FLAG },
    ],
  },
];