version: '3.8'

services:
  commandcrafter:
    build:
      context: .
      args:
        VITE_API_KEY: ${VITE_API_KEY}
    container_name: linux-command-crafter
    ports:
      - "7256:80"
    restart: always
