import { Tutorial } from './types';

export const TUTORIALS: Tutorial[] = [
  {
    name: 'mv',
    title: 'Getting Started with mv',
    content: [
      { type: 'heading', text: 'What is mv?' },
      { type: 'paragraph', text: 'The `mv` command is one of the most basic and frequently used commands. Its primary purpose is to move files or directories from one location to another. You can also use it to rename files and directories.' },
      { type: 'heading', text: 'Basic Usage: Renaming a File' },
      { type: 'paragraph', text: 'To rename a file, you specify the current name and the new name.' },
      { type: 'code', text: 'mv old_filename.txt new_filename.txt' },
      { type: 'heading', text: 'Basic Usage: Moving a File' },
      { type: 'paragraph', text: 'To move a file into a directory, specify the file and the destination directory.' },
      { type: 'code', text: 'mv my_document.txt ./documents/' },
      { type: 'heading', text: 'Common Options' },
      { type: 'paragraph', text: 'The builder helps you add options. A common one is `-i` (interactive) which will ask you for confirmation before overwriting an existing file.' },
      { type: 'code', text: 'mv -i important.log ./archives/' },
      { type: 'paragraph', text: 'Another useful option is `-v` (verbose), which tells you exactly what `mv` is doing.' },
      { type: 'code', text: 'mv -v project_alpha/ project_beta/' },
    ],
  },
  {
    name: 'cp',
    title: 'Getting Started with cp',
    content: [
        { type: 'heading', text: 'What is cp?' },
        { type: 'paragraph', text: 'The `cp` command is used to copy files and directories. It creates an exact copy of a file or a directory\'s contents.' },
        { type: 'heading', text: 'Basic Usage: Copying a File' },
        { type: 'paragraph', text: 'To copy a file in the current directory, provide the source file and a name for the new copy.' },
        { type: 'code', text: 'cp source.txt destination.txt' },
        { type: 'heading', text: 'Basic Usage: Copying a Directory' },
        { type: 'paragraph', text: 'To copy a directory and all of its contents, you must use the `-r` (recursive) option.' },
        { type: 'code', text: 'cp -r my_photos/ my_photos_backup/' },
        { type: 'heading', text: 'Common Options' },
        { type: 'paragraph', text: 'Use `-v` (verbose) to see which files are being copied. Use `-a` (archive) to preserve file attributes like permissions and timestamps, which is great for backups.' },
        { type: 'code', text: 'cp -av my_project/ /mnt/backup/' },
    ],
  },
    {
    name: 'git',
    title: 'Getting Started with Git',
    content: [
        { type: 'heading', text: 'What is Git?' },
        { type: 'paragraph', text: 'Git is a distributed version control system for tracking changes in source code during software development. It\'s designed for coordinating work among programmers, but it can be used to track changes in any set of files.' },
        { type: 'heading', text: 'Common Workflow' },
        { type: 'paragraph', text: 'A typical workflow involves cloning a repository, making changes, adding them to a "staging area", committing them to your local repository, and then pushing them to a remote server.' },
        { type: 'heading', text: 'Using the Builder' },
        { type: 'paragraph', text: 'This builder helps you construct commands for the most common operations. Select a subcommand from the dropdown to get started.' },
        { type: 'code', text: '# 1. Clone a repository to get a local copy\ngit clone https://github.com/example/repo.git\n\n# 2. Make your changes, then add them\ngit add .\n\n# 3. Commit your changes with a message\ngit commit -m "Add new feature"\n\n# 4. Push your commit to the remote server\ngit push origin main' },
        { type: 'heading', text: 'Cloning Private Repositories' },
        { type: 'paragraph', text: 'When cloning a private repository over HTTPS, you can provide a Personal Access Token (PAT) or API Key in the "API Key / Token" field. The builder will automatically embed this key into the repository URL, allowing you to authenticate without a password prompt.' },
        { type: 'code', text: '# Example command for cloning a private repo with a token\ngit clone https://ghp_YourToken..._@github.com/user/private-repo.git' },
    ],
  },
  {
    name: 'scp',
    title: 'Getting Started with scp',
    content: [
        { type: 'heading', text: 'What is scp?' },
        { type: 'paragraph', text: '`scp` stands for "secure copy". It is a command-line utility that allows you to securely copy files and directories between two locations, usually between your local machine and a remote server. It uses SSH (Secure Shell) for data transfer, so it provides the same level of security.' },
        { type: 'heading', text: 'Basic Syntax' },
        { type: 'paragraph', text: 'The syntax is very similar to `cp`. For remote paths, you specify the username and host, separated by an `@`, followed by a colon and the path.' },
        { type: 'code', text: '# Copy a local file to a remote server\nscp /path/to/local/file.txt user@remote_host:/path/to/remote/directory/\n\n# Copy a remote file to your local machine\nscp user@remote_host:/path/to/remote/file.txt /path/to/local/directory/' },
        { type: 'heading', text: 'Copying Directories' },
        { type: 'paragraph', text: 'Just like with `cp`, you need to use the `-r` (recursive) flag to copy an entire directory and its contents.' },
        { type: 'code', text: 'scp -r /path/to/local_project user@remote_host:/home/user/projects/' },
        { type: 'heading', text: 'Important Options' },
        { type: 'paragraph', text: 'Use `-P` (uppercase) to specify a port if your remote SSH server is not running on the default port 22. Use `-C` for compression to speed up the transfer over slow networks.' },
        { type: 'code', text: 'scp -P 2222 -C report.zip user@remote_host:/backups/' },
    ],
  },
  {
    name: 'rsync',
    title: 'Getting Started with rsync',
    content: [
        { type: 'heading', text: 'What is rsync?' },
        { type: 'paragraph', text: '`rsync` is a powerful tool for synchronizing files and directories between two locations. It\'s efficient because it only copies the parts of files that have changed.' },
        { type: 'heading', text: 'Basic Usage: Local Sync' },
        { type: 'paragraph', text: 'To sync two directories on your local machine, use the `-a` (archive) and `-v` (verbose) flags.' },
        { type: 'code', text: 'rsync -av /home/user/docs/ /media/backup/docs/' },
        { type: 'heading', text: 'Key Options for Backups' },
        { type: 'paragraph', text: 'The combination `-avz` is very common. `a` is for archive, `v` is for verbose, and `z` compresses the data to speed up the transfer.' },
        { type: 'code', text: 'rsync -avz --progress user@server:/remote/dir/ ./local/dir/' },
        { type: 'paragraph', text: 'The `--progress` flag shows you the transfer progress, and `--delete` will remove files from the destination if they no longer exist at the source.' },
    ],
  },
    {
    name: 'sed',
    title: 'Getting Started with sed',
    content: [
        { type: 'heading', text: 'What is sed?' },
        { type: 'paragraph', text: '`sed` stands for "stream editor". It\'s a powerful command-line tool for parsing and transforming text. Its most common use is for search and replace operations on files or input streams.' },
        { type: 'heading', text: 'Basic Syntax: Search and Replace' },
        { type: 'paragraph', text: 'The core of `sed` is the substitute command, `s`. The syntax is `s/SEARCH_PATTERN/REPLACEMENT/FLAGS`.' },
        { type: 'code', text: '# Replaces the first occurrence of "apple" with "orange" on each line\nsed \'s/apple/orange/\' input.txt' },
        { type: 'heading', text: 'Common Flags' },
        { type: 'paragraph', text: 'Flags modify the behavior of the substitution:' },
        { type: 'paragraph', text: '`g` (Global): Replaces all occurrences of the pattern on a line, not just the first one.' },
        { type: 'paragraph', text: '`i` (Case-insensitive): Matches the search pattern regardless of case.' },
        { type: 'code', text: '# Replace all occurrences of "error" (case-insensitive) with "warning"\nsed \'s/error/warning/gi\' system.log' },
        { type: 'heading', text: 'Editing Files In-Place' },
        { type: 'paragraph', text: 'By default, `sed` prints the result to the standard output. To modify the file directly, use the `-i` (in-place) flag. Be careful, as this overwrites the original file! It\'s recommended to use a full path to your file to avoid mistakes.' },
        { type: 'code', text: 'sed -i \'s/old_url/new_url/g\' /etc/nginx/sites-available/default' },
    ],
  },
  {
    name: 'tar',
    title: 'Getting Started with tar',
    content: [
        { type: 'heading', text: 'What is tar?' },
        { type: 'paragraph', text: '`tar` stands for "tape archive". It\'s used to bundle a collection of files and directories into a single archive file, often called a "tarball".' },
        { type: 'heading', text: 'Creating an Archive' },
        { type: 'paragraph', text: 'To create an archive, you need three main flags: `c` (create), `v` (verbose, to see the files), and `f` (file, to specify the archive name).' },
        { type: 'code', text: 'tar -cvf my_archive.tar /path/to/directory' },
        { type: 'heading', text: 'Extracting an Archive' },
        { type: 'paragraph', text: 'To extract files from an archive, use `x` (extract) instead of `c`.' },
        { type: 'code', text: 'tar -xvf my_archive.tar' },
        { type: 'heading', text: 'Compression' },
        { type: 'paragraph', text: '`tar` by itself doesn\'t compress. You can add another flag to compress the archive. The most common is `z` for gzip, which creates a `.tar.gz` file.' },
        { type: 'code', text: 'tar -czvf my_archive.tar.gz /path/to/stuff' },
        { type: 'heading', text: 'Multi-threaded Compression' },
        { type: 'paragraph', text: 'For large archives, you can speed up compression by using a multi-threaded program like `pigz` (a parallel `gzip`). Use the `--use-compress-program` flag for this.' },
        { type: 'code', text: 'tar -cvf my_archive.tar.gz --use-compress-program="pigz" /path/to/large_directory' },
    ],
  },
  {
    name: 'gzip',
    title: 'Getting Started with gzip',
    content: [
        { type: 'heading', text: 'What is gzip?' },
        { type: 'paragraph', text: '`gzip` is a popular compression utility. It takes a single file and creates a compressed version with a `.gz` extension, deleting the original by default.' },
        { type: 'heading', text: 'Compressing a File' },
        { type: 'paragraph', text: 'Simply run `gzip` on a file.' },
        { type: 'code', text: 'gzip large_log_file.log' },
        { type: 'paragraph', text: 'This will create `large_log_file.log.gz` and remove the original. Use the `-k` (keep) flag to keep the original file.' },
        { type: 'code', text: 'gzip -k large_log_file.log' },
        { type: 'heading', text: 'Decompressing a File' },
        { type: 'paragraph', text: 'To decompress a `.gz` file, use the `-d` (decompress) flag.' },
        { type: 'code', text: 'gzip -d large_log_file.log.gz' },
    ],
  },
  {
    name: 'grep',
    title: 'Getting Started with grep',
    content: [
        { type: 'heading', text: 'What is grep?' },
        { type: 'paragraph', text: '`grep` stands for "global regular expression print". It\'s a powerful tool for searching for a specific text pattern within files. It reads files line by line and prints any line that contains the pattern.' },
        { type: 'heading', text: 'Basic Usage' },
        { type: 'paragraph', text: 'The basic syntax is `grep "pattern" filename`.' },
        { type: 'code', text: 'grep "error" /var/log/syslog' },
        { type: 'heading', text: 'Searching Recursively' },
        { type: 'paragraph', text: 'To search for a pattern in all files within a directory and its subdirectories, use the `-r` (recursive) flag.' },
        { type: 'code', text: 'grep -r "API_KEY" /etc/my-app/' },
        { type: 'heading', text: 'Common and Useful Flags' },
        { type: 'paragraph', text: 'The builder provides checkboxes for these common flags:' },
        { type: 'paragraph', text: '`-i`: Ignore case sensitivity.' },
        { type: 'paragraph', text: '`-v`: Invert the match, showing lines that *do not* contain the pattern.' },
        { type: 'paragraph', text: '`-l`: List only the names of files that contain the pattern.' },
        { type: 'paragraph', text: '`-n`: Prepend each matching line with its line number.' },
        { type: 'paragraph', text: '`-w`: Match only whole words.' },
        { type: 'code', text: '# Find all files in the current directory containing "TODO" (case-insensitive)\ngrep -ril "TODO" .' },
    ],
  },
  {
    name: 'find',
    title: 'Getting Started with find',
    content: [
        { type: 'heading', text: 'What is find?' },
        { type: 'paragraph', text: 'The `find` command is used to search for files and directories within a directory hierarchy based on a wide range of criteria like name, type, size, modification time, and more.' },
        { type: 'heading', text: 'Basic Syntax' },
        { type: 'paragraph', text: 'The syntax is `find [starting-path] [expression]`. The expression is made up of tests and actions. The builder helps you create common expressions.' },
        { type: 'heading', text: 'Searching by Name' },
        { type: 'paragraph', text: 'The most common use is searching for a file by its name. Use `-name` for a case-sensitive search and `-iname` for case-insensitive. You can use wildcards like `*`.' },
        { type: 'code', text: '# Find all files ending with .log in the /var/log directory\nfind /var/log -name "*.log"' },
        { type: 'heading', text: 'Searching by Type' },
        { type: 'paragraph', text: 'You can limit your search to only files or only directories using the `-type` test.' },
        { type: 'code', text: '# Find all directories inside your home directory\nfind ~ -type d' },
        { type: 'paragraph', text: '`f` is for regular files, `d` is for directories, and `l` is for symbolic links.' },
        { type: 'code', text: '# Find all Python files that are not in a venv directory\nfind . -type f -name "*.py"' },
    ],
  },
  {
    name: 'chmod',
    title: 'Getting Started with chmod',
    content: [
        { type: 'heading', text: 'What is chmod?' },
        { type: 'paragraph', text: 'The `chmod` command, short for "change mode", is used to change the access permissions of files and directories.' },
        { type: 'heading', text: 'Understanding Permissions' },
        { type: 'paragraph', text: 'Permissions are defined for three classes of users: the `user` (owner), the `group`, and `others`. For each class, three permissions can be set: `read (r)`, `write (w)`, and `execute (x)`.' },
        { type: 'heading', text: 'Octal Mode' },
        { type: 'paragraph', text: 'In octal mode, permissions are represented by a 3-digit number. Each digit represents a user class (User, Group, Other). The value of the digit is the sum of its permissions: `read=4`, `write=2`, `execute=1`.' },
        { type: 'code', text: '# 7 = 4+2+1 (rwx)\n# 6 = 4+2 (rw-)\n# 5 = 4+1 (r-x)\n# 4 = 4 (r--)\n\n# Set rwxr-xr-x permissions for my_script.sh\nchmod 755 my_script.sh' },
        { type: 'heading', text: 'Symbolic Mode' },
        { type: 'paragraph', text: 'Symbolic mode is more readable. You specify which user class (`u`, `g`, `o`, `a` for all), an operator (`+` to add, `-` to remove, `=` to set), and which permissions (`r`, `w`, `x`). The builder makes this very easy!' },
        // FIX: Corrected a typo from `type::` to `type:` to match the TutorialContent interface.
        { type: 'code', text: '# Add execute permission for the user (owner)\nchmod u+x my_script.sh\n\n# Remove write permission for group and others\nchmod go-w my_config.conf' },
        { type: 'heading', text: 'Recursive Changes' },
        { type: 'paragraph', text: 'Use the `-R` flag to apply permission changes to a directory and all of its contents recursively. Be careful with this!' },
        { type: 'code', text: 'chmod -R 755 /var/www/my_project' },
    ],
  },
  {
    name: 'bash',
    title: 'Visual Bash Script Builder',
    content: [
        { type: 'heading', text: 'What is a Bash Script?' },
        { type: 'paragraph', text: 'A Bash script is a plain text file containing a series of commands. These commands are a mixture of commands you would type yourself on the command line (like `ls` or `cp`) and programming constructs like loops, and conditional statements. This builder lets you create them visually!' },
        { type: 'heading', text: 'The Block-Based Approach' },
        { type: 'paragraph', text: 'Instead of writing code, you add "blocks" to build your script. Each block represents a part of the script, like a variable, a comment, or an `if` statement. You can add, remove, and reorder these blocks to create the logic you need.' },
        { type: 'heading', text: 'Available Blocks' },
        { type: 'paragraph', text: 'The builder includes essential blocks: variables, echo, read user input, comments, and general commands. It also includes powerful logic blocks like `if/else` and `for` loops.' },
        { type: 'heading', text: 'Nested Logic' },
        { type: 'paragraph', text: 'The `if/else` and `for` blocks are special: they are containers. You can add other blocks *inside* of them to create nested logic. For example, you can place an `echo` block inside the `then` part of an `if` block.' },
        { type: 'heading', text: 'Example: A Simple Backup Script' },
        { type: 'paragraph', text: 'Here is how you might build a simple script:' },
        { type: 'code', text: '#!/bin/bash\n\n# A simple backup script\n\nBACKUP_DIR="/mnt/backups"\nSOURCE_DIR="/home/user/documents"\n\n# Check if backup directory exists\nif [ ! -d "$BACKUP_DIR" ]; then\n  echo "Backup directory does not exist!"\nfi\n\nrsync -avz "$SOURCE_DIR" "$BACKUP_DIR"\necho "Backup complete!"' },
        { type: 'paragraph', text: 'To create this, you would add a Comment block, two Variable blocks, an If block (with an Echo block inside its "then" section), and finally two Command blocks.' },
    ],
  },
  {
    name: 'ffmpeg',
    title: 'Getting Started with FFmpeg',
    content: [
        { type: 'heading', text: 'What is FFmpeg?' },
        { type: 'paragraph', text: 'FFmpeg is the leading multimedia framework, able to decode, encode, transcode, mux, demux, stream, filter and play pretty much anything that humans and machines have created. It is an extremely powerful command-line tool for handling video and audio files.' },
        { type: 'heading', text: 'Basic Syntax' },
        { type: 'paragraph', text: 'The basic structure of an FFmpeg command is `ffmpeg [global_options] [input_file_options] -i [input_url] [output_file_options] [output_url]`.' },
        { type: 'heading', text: 'Example: Converting Video Format' },
        { type: 'paragraph', text: 'This is one of the most common uses. The `-i` flag specifies the input file.' },
        { type: 'code', text: 'ffmpeg -i input.mov output.mp4' },
        { type: 'heading', text: 'Example: Extracting Audio' },
        { type: 'paragraph', text: 'You can easily strip the audio from a video file. `-vn` means "no video", and `-acodec copy` means we copy the audio stream without re-encoding it.' },
        { type: 'code', text: 'ffmpeg -i input.mp4 -vn -acodec copy output.aac' },
        { type: 'heading', text: 'Upscaling with Hardware Acceleration' },
        { type: 'paragraph', text: 'The builder can help you create commands for upscaling video. This is computationally expensive and works best with a dedicated GPU. If you have a supported NVIDIA card, you can use `cuda` for a significant speed boost.' },
        { type: 'code', text: '# Upscale a video to 4K using the NVIDIA CUDA hardware accelerator\nffmpeg -hwaccel cuda -i input.mp4 -vf "scale_cuda=3840:2160" -c:v h264_nvenc output_4k.mp4' },
    ],
  },
  {
    name: 'ansible-playbook',
    title: 'Getting Started with Ansible',
    content: [
        { type: 'heading', text: 'What is Ansible?' },
        { type: 'paragraph', text: 'Ansible is a powerful automation tool used for tasks like configuration management, application deployment, and task automation. Instead of single commands, you write "playbooks" in the YAML format to describe the desired state of your systems.' },
        { type: 'heading', text: 'Using the Builder' },
        { type: 'paragraph', text: 'This builder simplifies creating playbooks. First, define the general settings for your "play" (the target hosts and if you need admin privileges). Then, add tasks using the preset buttons. Each task is a single action, like installing a package or starting a service. The builder will generate the correct YAML format for you.' },
        { type: 'heading', text: 'Anatomy of a Playbook' },
        { type: 'paragraph', text: 'Here is what the structure of a playbook generated by the builder looks like:' },
        { type: 'code', text: '---\n- name: My First Playbook\n  hosts: all\n  become: true\n\n  tasks:\n    - name: Ensure apache is installed\n      ansible.builtin.package:\n        name: apache2\n        state: present\n\n    - name: Ensure apache is running\n      ansible.builtin.service:\n        name: apache2\n        state: started' },
        { type: 'heading', text: 'Running a Playbook' },
        { type: 'paragraph', text: 'To run a playbook you\'ve created, you save it as a file (e.g., `my_playbook.yml`) and use the `ansible-playbook` command. You also need an "inventory" file that lists the servers Ansible should connect to.' },
        { type: 'code', text: 'ansible-playbook -i /path/to/inventory my_playbook.yml' },
    ],
  },
  {
    name: 'lxc',
    title: 'Getting Started with LXC',
    content: [
        { type: 'heading', text: 'What is lxc launch?' },
        { type: 'paragraph', text: '`lxc launch` is the command used to create and start a new system container or virtual machine from a specified image. It\'s the primary way to get a new instance running.' },
        // FIX: Corrected typo from `type::` to `type:`.
        { type: 'heading', text: 'Basic Usage' },
        { type: 'paragraph', text: 'You need to provide an image name and a name for your new container. Image names are typically in the format `distribution:version`.' },
        { type: 'code', text: 'lxc launch ubuntu:22.04 web-server' },
        { type: 'heading', text: 'Setting Resource Limits' },
        { type: 'paragraph', text: 'The builder makes it easy to customize your container\'s resources. You can specify CPU cores, memory, and storage size directly. These options translate into configuration flags passed to the launch command.' },
        { type: 'code', text: '# Launch a container with 2 CPU cores, 1024MB of RAM, and a 20GB root disk\nlxc launch ubuntu:22.04 my-app -c limits.cpu=2 -c limits.memory=1024MB --device root,size=20GB' },
        { type: 'heading', text: 'Launching a Virtual Machine' },
        { type: 'paragraph', text: 'You can launch a VM instead of a container by using the `lxc launch --vm` command, though the builder currently focuses on container creation.' },
    ],
  },
  {
    name: 'ufw',
    title: 'Getting Started with UFW',
    content: [
        { type: 'heading', text: 'What is UFW?' },
        { type: 'paragraph', text: 'UFW stands for "Uncomplicated Firewall". It\'s a user-friendly interface for managing iptables, making firewall management much simpler.' },
        { type: 'heading', text: 'Checking the Status' },
        { type: 'paragraph', text: 'Before making changes, it\'s always good to check the current status of the firewall. It will tell you if it\'s active and list all the current rules.' },
        { type: 'code', text: 'ufw status' },
        { type: 'heading', text: 'Enabling and Disabling' },
        { type: 'paragraph', text: 'You can easily enable or disable the firewall. Note that enabling it might lock you out if you haven\'t allowed SSH access first! Use the common ports helper in the builder to quickly find the port for SSH (22).' },
        { type: 'code', text: 'ufw enable\nufw disable' },
        { type: 'heading', text: 'Allowing and Denying Ports' },
        { type: 'paragraph', text: 'The most common use is to allow or deny traffic on specific ports. You can specify the port and optionally the protocol (tcp or udp).' },
        { type: 'code', text: '# Allow SSH connections\nufw allow 22/tcp\n\n# Allow HTTP traffic\nufw allow http\n\n# Deny outgoing mail\nufw deny out 25' },
    ],
  },
  {
    name: 'crontab',
    title: 'Getting Started with crontab',
    content: [
        { type: 'heading', text: 'What is cron?' },
        { type: 'paragraph', text: '`cron` is a time-based job scheduler in Unix-like operating systems. A `crontab` is a file that contains the schedule of entries to be run and at specified times.' },
        { type: 'heading', text: 'The Crontab Format' },
        { type: 'paragraph', text: 'A crontab line has 5 time-and-date fields, followed by the command to be run. The builder helps you set these values correctly.' },
        { type: 'code', text: '# ┌───────────── minute (0 - 59)\n# │ ┌───────────── hour (0 - 23)\n# │ │ ┌───────────── day of month (1 - 31)\n# │ │ │ ┌───────────── month (1 - 12)\n# │ │ │ │ ┌───────────── day of week (0 - 6) (Sunday to Saturday, 7 is also Sunday)\n# │ │ │ │ │\n# │ │ │ │ │\n# * * * * *  command_to_execute' },
        { type: 'heading', text: 'Example: Run a script every day at 2 AM' },
        { type: 'paragraph', text: 'The minute is 0, the hour is 2, and all other fields are wildcards (*).' },
        { type: 'code', text: '0 2 * * * /home/user/scripts/backup.sh' },
        { type: 'heading', text: 'Example: Run every 15 minutes' },
        { type: 'paragraph', text: 'You can use the `*/n` syntax to mean "every n".' },
        { type: 'code', text: '*/15 * * * * /home/user/scripts/check_status.sh' },
    ],
  },
  {
    name: 'ip',
    title: 'Getting Started with the ip command',
    content: [
        { type: 'heading', text: 'What is ip?' },
        { type: 'paragraph', text: 'The `ip` command is a modern and powerful tool for network configuration on Linux. It has replaced older tools like `ifconfig` and `route`. It is used to view and manipulate routing, network devices, interfaces, and tunnels.' },
        { type: 'heading', text: 'Using the Builder' },
        { type: 'paragraph', text: 'The `ip` command has many subcommands and options. This builder is organized by the main "objects" that `ip` manages: `addr` (IP addresses), `link` (network interfaces), and `route` (routing table).' },
        { type: 'heading', text: 'Example: Viewing IP Addresses' },
        { type: 'paragraph', text: 'The most common use is to see the IP addresses assigned to your network interfaces.' },
        { type: 'code', text: '# Show information for all interfaces\nip addr show\n\n# Show information for a specific interface (e.g., eth0)\nip addr show dev eth0' },
        { type: 'heading', text: 'Example: Bringing an Interface Up or Down' },
        { type: 'paragraph', text: 'You can enable or disable a network interface using the `link` object.' },
        { type: 'code', text: '# Bring interface eth0 down\nip link set dev eth0 down\n\n# Bring interface eth0 up\nip link set dev eth0 up' },
         { type: 'heading', text: 'Example: Managing Routes' },
        { type: 'paragraph', text: 'You can view your system\'s routing table or add new routes.' },
        { type: 'code', text: '# Display the routing table\nip route show\n\n# Add a default route via a gateway\nip route add default via 192.168.1.1' },
    ],
  },
];