"""Tutorial content. Direct port of tutorials.ts.

Each tutorial is a dict with `name`, `title`, and `content` (a list of blocks
with `type` in {heading, paragraph, code, tip, warning, note}).
"""
from __future__ import annotations

TUTORIALS: list[dict[str, object]] = [
    {
        "name": "ssh",
        "title": "SSH — Secure Shell Complete Guide",
        "content": [
            {"type": "heading", "text": "SYNOPSIS"},
            {"type": "code", "text": "ssh [OPTIONS] [user@]hostname [command]"},
            {"type": "heading", "text": "What is SSH?"},
            {"type": "paragraph", "text": "SSH (Secure Shell) is a cryptographic network protocol for operating network services securely over an unsecured network. It is the standard way to log into remote Linux/Unix systems, execute commands, and transfer files."},
            {"type": "note", "text": "SSH listens on port 22 by default. All traffic is encrypted end-to-end using public-key cryptography."},
            {"type": "heading", "text": "1. Connecting to a Remote Host"},
            {"type": "paragraph", "text": "The most basic form: specify the remote host. If you omit the username, your local username is used."},
            {"type": "code", "text": "# Connect as current user\nssh 192.168.1.10\n\n# Connect as a specific user\nssh deploy@192.168.1.10\n\n# Connect on a non-standard port\nssh -p 2222 deploy@192.168.1.10"},
            {"type": "heading", "text": "2. Key-Based Authentication (Recommended)"},
            {"type": "paragraph", "text": "Password authentication is vulnerable to brute-force attacks. Key-based auth is far more secure and convenient. It works by placing your public key on the server; only the holder of the matching private key can authenticate."},
            {"type": "code", "text": "# Step 1: Generate a key pair on YOUR local machine\nssh-keygen -t ed25519 -C \"your_email@example.com\"\n# (use RSA-4096 if ed25519 is not supported)\nssh-keygen -t rsa -b 4096 -f ~/.ssh/id_rsa_myserver\n\n# Step 2: Copy your public key to the server\nssh-copy-id user@remote_host\n\n# Or do it manually:\ncat ~/.ssh/id_ed25519.pub | ssh user@remote \"mkdir -p ~/.ssh && cat >> ~/.ssh/authorized_keys && chmod 600 ~/.ssh/authorized_keys\""},
            {"type": "tip", "text": "Use a passphrase when generating your key. The passphrase is stored locally and never sent to the server. Use ssh-agent to avoid typing it repeatedly."},
            {"type": "heading", "text": "3. The SSH Config File (~/.ssh/config)"},
            {"type": "paragraph", "text": "Instead of typing long ssh commands, define hosts in your SSH config file. This lets you connect with short aliases and pre-set all options."},
            {"type": "code", "text": "# ~/.ssh/config\n\nHost myserver\n    HostName 192.168.1.10\n    User deploy\n    Port 2222\n    IdentityFile ~/.ssh/id_ed25519_myserver\n    ServerAliveInterval 60\n\nHost bastion\n    HostName bastion.example.com\n    User ec2-user\n    IdentityFile ~/.ssh/id_rsa_aws"},
            {"type": "code", "text": "# Now you can simply type:\nssh myserver\n# Instead of: ssh -p 2222 -i ~/.ssh/id_ed25519_myserver deploy@192.168.1.10"},
            {"type": "note", "text": "Permissions on ~/.ssh/config must be 600 (readable only by you): chmod 600 ~/.ssh/config"},
            {"type": "heading", "text": "4. Port Forwarding (Tunneling)"},
            {"type": "paragraph", "text": "SSH can forward TCP traffic through an encrypted tunnel. This is one of its most powerful features."},
            {"type": "paragraph", "text": "LOCAL FORWARDING (-L): Forwards a local port to a remote address."},
            {"type": "code", "text": "# Access a remote database on localhost:5432\n# (remote_db_host is reachable FROM the SSH server)\nssh -L 5432:remote_db_host:5432 user@ssh_server\n\n# Now connect locally:\npsql -h localhost -p 5432 -U dbuser mydb"},
            {"type": "paragraph", "text": "REMOTE FORWARDING (-R): Exposes a local service to the remote server."},
            {"type": "code", "text": "# Expose your local web server (port 3000) on the remote server port 9000\nssh -R 9000:localhost:3000 user@ssh_server"},
            {"type": "paragraph", "text": "DYNAMIC FORWARDING (-D): Creates a SOCKS5 proxy."},
            {"type": "code", "text": "# Create a SOCKS5 proxy on local port 1080\nssh -D 1080 -N user@ssh_server\n# Configure your browser to use SOCKS5 proxy at 127.0.0.1:1080"},
            {"type": "heading", "text": "5. Jumping Through Bastion Hosts (-J)"},
            {"type": "paragraph", "text": "Use -J to chain through an intermediate server (bastion/jump host) to reach a private server."},
            {"type": "code", "text": "# Connect to private-server via bastion\nssh -J ec2-user@bastion.example.com ubuntu@10.0.0.50\n\n# Or in ~/.ssh/config:\n# Host private-server\n#     ProxyJump bastion"},
            {"type": "heading", "text": "6. Running Commands Without an Interactive Shell"},
            {"type": "code", "text": "# Run a single command and exit\nssh user@host \"df -h\"\n\n# Run a complex script remotely\nssh user@host \"bash -s\" < local_script.sh\n\n# Non-interactive mode (no TTY allocation) - useful in scripts\nssh -o BatchMode=yes user@host \"uptime\""},
            {"type": "heading", "text": "7. Server Hardening: sshd_config"},
            {"type": "paragraph", "text": "These settings in /etc/ssh/sshd_config significantly improve server security."},
            {"type": "code", "text": "# /etc/ssh/sshd_config -- recommended settings\nPort 2222                        # Non-standard port\nPermitRootLogin no               # Never allow root login\nPasswordAuthentication no        # Require key-based auth\nPubkeyAuthentication yes\nX11Forwarding no\nMaxAuthTries 3\nAllowUsers deploy admin          # Whitelist specific users"},
            {"type": "warning", "text": "Always test your sshd_config changes in a NEW session before closing your current connection. A broken config will lock you out. Run: sudo sshd -t to test the config before restarting."},
            {"type": "heading", "text": "8. SSH Agent"},
            {"type": "code", "text": "# Start the agent (usually done automatically by your shell)\neval \"$(ssh-agent -s)\"\n\n# Add your key to the agent (avoids passphrase prompts)\nssh-add ~/.ssh/id_ed25519\n\n# List loaded keys\nssh-add -l\n\n# Forward your agent to the remote server\nssh -A user@host"},
            {"type": "tip", "text": "Add \"AddKeysToAgent yes\" and \"IdentityFile ~/.ssh/id_ed25519\" to your ~/.ssh/config to have keys loaded automatically on first use."},
        ],
    },
    {
        "name": "mv",
        "title": "mv — Move and Rename Files",
        "content": [
            {"type": "heading", "text": "SYNOPSIS"},
            {"type": "code", "text": "mv [OPTIONS] SOURCE DESTINATION\nmv [OPTIONS] SOURCE... DIRECTORY"},
            {"type": "heading", "text": "Description"},
            {"type": "paragraph", "text": "mv moves (renames) SOURCE to DESTINATION, or moves multiple SOURCEs to DIRECTORY. It can operate on both files and directories. Unlike cp, mv does not consume extra disk space for local moves on the same filesystem — the kernel simply updates the directory entry."},
            {"type": "note", "text": "Moving across different filesystems performs a copy + delete. On the same filesystem, mv is essentially instantaneous regardless of file size."},
            {"type": "heading", "text": "Renaming a File"},
            {"type": "code", "text": "# Rename in the current directory\nmv old_name.txt new_name.txt\n\n# Rename a directory\nmv project_v1/ project_v2/"},
            {"type": "heading", "text": "Moving Files"},
            {"type": "code", "text": "# Move a file into a directory\nmv report.pdf ~/Documents/\n\n# Move multiple files to a directory\nmv file1.txt file2.txt file3.txt ~/archive/\n\n# Move all .log files to /var/archive\nmv /var/log/*.log /var/archive/"},
            {"type": "heading", "text": "Key Options"},
            {"type": "paragraph", "text": "-i (interactive): Prompts before overwriting an existing file."},
            {"type": "paragraph", "text": "-n (no-clobber): Never overwrites existing files silently."},
            {"type": "paragraph", "text": "-f (force): Skips the confirmation prompt. Overrides -i and -n."},
            {"type": "paragraph", "text": "-v (verbose): Prints each file name as it is moved."},
            {"type": "paragraph", "text": "-u (update): Moves only if source is newer than destination, or destination does not exist."},
            {"type": "code", "text": "# Safe move: ask before overwriting\nmv -i *.conf /etc/myapp/\n\n# Verbose move with update check\nmv -uv /tmp/new_config.conf /etc/myapp/config.conf"},
            {"type": "warning", "text": "mv overwrites the destination without warning by default. If you run \"mv file.txt existing.txt\", existing.txt is silently destroyed. Always use -i when unsure."},
            {"type": "tip", "text": "Add \"alias mv='mv -i'\" to your ~/.bashrc to always be prompted before overwriting."},
        ],
    },
    {
        "name": "cp",
        "title": "cp — Copy Files and Directories",
        "content": [
            {"type": "heading", "text": "SYNOPSIS"},
            {"type": "code", "text": "cp [OPTIONS] SOURCE DESTINATION\ncp [OPTIONS] SOURCE... DIRECTORY"},
            {"type": "heading", "text": "Description"},
            {"type": "paragraph", "text": "cp copies SOURCE to DESTINATION. Unlike mv, the original source is preserved. It is one of the most used file management commands."},
            {"type": "heading", "text": "Copying Files"},
            {"type": "code", "text": "# Copy a file\ncp source.txt destination.txt\n\n# Copy to a directory\ncp report.pdf ~/Documents/"},
            {"type": "heading", "text": "Copying Directories"},
            {"type": "paragraph", "text": "Copying a directory requires the -r (recursive) flag, which copies the directory and all its contents."},
            {"type": "code", "text": "# Copy a directory and its contents\ncp -r my_project/ /mnt/backup/my_project/\n\n# Verbose recursive copy\ncp -rv src/ dest/"},
            {"type": "warning", "text": "Omitting -r when copying a directory will give: \"cp: my_dir is a directory (not copied).\" The copy will fail."},
            {"type": "heading", "text": "Preserving Attributes (-a Archive Mode)"},
            {"type": "paragraph", "text": "The -a (archive) flag preserves permissions, ownership, timestamps, and symlinks. It is equivalent to -dR --preserve=all. Essential for backups."},
            {"type": "code", "text": "# Perfect backup copy\ncp -a /home/user/ /mnt/backup/user/\n\n# -a includes -r\ncp -av /var/www/html/ /var/www/html.bak/"},
            {"type": "heading", "text": "Key Options Reference"},
            {"type": "paragraph", "text": "-i: Prompt before overwrite. -n: Never overwrite existing files. -u: Copy only when source is newer than destination. -l: Create hard links instead of copying. -s: Create symbolic links instead of copying."},
            {"type": "tip", "text": "For large directory trees, consider rsync instead of cp. rsync only transfers changed files, making it much faster for incremental backups."},
        ],
    },
    {
        "name": "tar",
        "title": "tar — Archiving Utility",
        "content": [
            {"type": "heading", "text": "SYNOPSIS"},
            {"type": "code", "text": "tar [OPERATION] [OPTIONS] [ARCHIVE] [FILES...]"},
            {"type": "heading", "text": "Description"},
            {"type": "paragraph", "text": "tar (Tape ARchive) creates, lists, and extracts archive files. It bundles multiple files into a single \".tar\" file (a tarball). Compression is applied separately through gzip (-z), bzip2 (-j), or xz (-J)."},
            {"type": "note", "text": "tar itself does NOT compress — it only archives. The -z/-j/-J flags pipe the archive through a compression program."},
            {"type": "heading", "text": "The Key Flags"},
            {"type": "paragraph", "text": "-c: Create a new archive. -x: Extract files. -t: List contents. -f ARCHIVE: Specifies the archive filename. -v: Verbose. -z: gzip (.tar.gz). -j: bzip2 (.tar.bz2). -J: xz (.tar.xz)."},
            {"type": "heading", "text": "Creating Archives"},
            {"type": "code", "text": "# Create a gzip-compressed archive of a directory\ntar -cvzf backup.tar.gz ./my_folder/\n\n# bzip2 (better ratio, slower)\ntar -cvjf backup.tar.bz2 ./my_folder/\n\n# Archive multiple items\ntar -cvzf everything.tar.gz /etc /home /var/www\n\n# Exclude specific directories\ntar -cvzf backup.tar.gz ./project/ --exclude=./project/node_modules --exclude=./project/.git"},
            {"type": "heading", "text": "Extracting Archives"},
            {"type": "code", "text": "# Extract to current directory\ntar -xvzf backup.tar.gz\n\n# Extract to a specific directory\ntar -xvzf backup.tar.gz -C /tmp/restore/\n\n# Extract a single file\ntar -xvzf backup.tar.gz ./my_folder/config.conf"},
            {"type": "heading", "text": "Listing Contents Without Extracting"},
            {"type": "code", "text": "# List contents\ntar -tvf backup.tar.gz\n\n# List and filter\ntar -tvf backup.tar.gz | grep \".conf\""},
            {"type": "tip", "text": "Modern tar can auto-detect compression — you can often omit -z/-j/-J: just use \"tar -xvf backup.tar.gz\" and tar will figure it out."},
            {"type": "heading", "text": "Strip Leading Directory Components on Extract"},
            {"type": "code", "text": "# Archive has: ./project/src/main.c\n# Extract and strip the first component:\ntar -xvzf backup.tar.gz --strip-components=1\n# Result: src/main.c (instead of project/src/main.c)"},
            {"type": "warning", "text": "Always check \"tar -tvf archive.tar.gz\" before extracting an untrusted archive. A malicious tarball can use absolute paths or \"../\" to overwrite system files."},
        ],
    },
    {
        "name": "grep",
        "title": "grep — Search Text Using Patterns",
        "content": [
            {"type": "heading", "text": "SYNOPSIS"},
            {"type": "code", "text": "grep [OPTIONS] PATTERN [FILE...]\ngrep [OPTIONS] -e PATTERN ... [FILE...]"},
            {"type": "heading", "text": "Description"},
            {"type": "paragraph", "text": "grep prints lines that match a pattern. It reads files (or stdin) line by line and outputs matching lines. Pattern is a POSIX Basic Regular Expression (BRE) by default; use -E for Extended Regular Expressions (ERE), or -P for Perl-compatible (PCRE)."},
            {"type": "heading", "text": "Basic Examples"},
            {"type": "code", "text": "# Search for a word in a file\ngrep \"error\" /var/log/syslog\n\n# Case-insensitive search\ngrep -i \"error\" /var/log/syslog\n\n# Match whole word only (not \"errors\" or \"terror\")\ngrep -w \"error\" /var/log/syslog"},
            {"type": "heading", "text": "Recursive Search"},
            {"type": "code", "text": "# Search all files in a directory tree\ngrep -r \"TODO\" ./src/\n\n# Recursive, case-insensitive, show filenames only\ngrep -ril \"api_key\" /etc/\n\n# Recursive with file extension filter\ngrep -r --include=\"*.py\" \"import os\" ./project/"},
            {"type": "heading", "text": "Context Lines"},
            {"type": "code", "text": "# Show 3 lines AFTER each match\ngrep -A 3 \"Exception\" app.log\n\n# Show 3 lines BEFORE each match\ngrep -B 3 \"Exception\" app.log\n\n# Show 3 lines BEFORE and AFTER each match\ngrep -C 3 \"Exception\" app.log"},
            {"type": "heading", "text": "Inverted Match and Counting"},
            {"type": "code", "text": "# Print lines that do NOT match\ngrep -v \"DEBUG\" app.log\n\n# Count matching lines\ngrep -c \"ERROR\" app.log\n\n# Show line numbers\ngrep -n \"WARN\" app.log"},
            {"type": "heading", "text": "Regular Expressions"},
            {"type": "code", "text": "# ERE: match lines starting with \"Error\" or \"Warning\"\ngrep -E \"^(Error|Warning)\" app.log\n\n# ERE: match an IP address pattern\ngrep -E \"([0-9]{1,3}\\.){3}[0-9]{1,3}\" access.log\n\n# Literal string (no regex interpretation)\ngrep -F \"192.168.1.1\" access.log"},
            {"type": "tip", "text": "Use grep -F (or fgrep) when searching for literal strings that contain regex special characters like ., *, [, ]. This avoids false matches and is faster."},
            {"type": "heading", "text": "Useful Combinations"},
            {"type": "code", "text": "# Find files containing a pattern, then edit them\ngrep -rl \"old_hostname\" /etc/ | xargs sed -i \"s/old_hostname/new_hostname/g\"\n\n# Count errors per log file\ngrep -rc \"ERROR\" /var/log/*.log\n\n# Exclude dirs\ngrep -r --include=\"*.conf\" --exclude-dir=\".git\" \"listen\" /etc/"},
        ],
    },
    {
        "name": "find",
        "title": "find — Search the Filesystem",
        "content": [
            {"type": "heading", "text": "SYNOPSIS"},
            {"type": "code", "text": "find [PATH...] [EXPRESSION]"},
            {"type": "heading", "text": "Description"},
            {"type": "paragraph", "text": "find searches the filesystem for files matching criteria: name, type, size, modification time, ownership, permissions, and more. It can also execute commands on found files."},
            {"type": "heading", "text": "Search by Name"},
            {"type": "code", "text": "# Case-sensitive name search\nfind /var/log -name \"*.log\"\n\n# Case-insensitive name search\nfind / -iname \"readme.md\"\n\n# Find files matching a pattern in current dir\nfind . -name \"config.*\""},
            {"type": "heading", "text": "Search by Type"},
            {"type": "code", "text": "# Find only files (f), directories (d), or symlinks (l)\nfind /home -type f -name \"*.sh\"\nfind /etc -type d\nfind /usr/bin -type l"},
            {"type": "heading", "text": "Search by Modification Time"},
            {"type": "paragraph", "text": "-mtime n: modified exactly n days ago. -mtime -n: less than n days ago. -mtime +n: more than n days ago."},
            {"type": "code", "text": "# Files modified in the last 7 days\nfind /var -type f -mtime -7\n\n# Files NOT modified in over 30 days\nfind /tmp -type f -mtime +30\n\n# Files modified in the last 60 minutes\nfind . -type f -mmin -60"},
            {"type": "heading", "text": "Search by Size"},
            {"type": "code", "text": "# Files larger than 100 MB\nfind / -type f -size +100M\n\n# Files smaller than 1 KB\nfind . -type f -size -1k\n\n# Files between 10M and 100M\nfind . -type f -size +10M -size -100M"},
            {"type": "heading", "text": "Search by Permissions and Ownership"},
            {"type": "code", "text": "# Files with SUID bit set (potential security risk)\nfind / -perm -4000 -type f\n\n# World-writable files\nfind / -perm -o+w -type f\n\n# Files owned by a specific user\nfind /home -user alice -type f"},
            {"type": "heading", "text": "Executing Commands on Results (-exec)"},
            {"type": "code", "text": "# Delete all .tmp files\nfind /tmp -name \"*.tmp\" -exec rm {} \\;\n\n# Batch mode (faster -- passes multiple files per call)\nfind . -name \"*.log\" -exec gzip {} +\n\n# Set permissions on all scripts\nfind ./scripts -name \"*.sh\" -exec chmod +x {} \\;\n\n# Find and grep inside matching files\nfind . -name \"*.conf\" -exec grep -l \"port 8080\" {} \\;"},
            {"type": "tip", "text": "Use -exec ... {} + instead of -exec ... {} \\; whenever possible. The + variant batches multiple filenames into one call, like xargs, and is significantly faster."},
            {"type": "warning", "text": "Be extremely careful with \"find / -exec rm {} \\;\". Always run with -print first to preview what will be deleted."},
        ],
    },
    {
        "name": "chmod",
        "title": "chmod — Change File Permissions",
        "content": [
            {"type": "heading", "text": "SYNOPSIS"},
            {"type": "code", "text": "chmod [OPTIONS] MODE FILE..."},
            {"type": "heading", "text": "Understanding Linux Permissions"},
            {"type": "paragraph", "text": "Every file and directory has permissions for three user classes: User (u) — the file owner; Group (g) — members of the file's group; Others (o) — everyone else."},
            {"type": "paragraph", "text": "For each class, three permissions can be set: read (r = 4), write (w = 2), execute (x = 1)."},
            {"type": "code", "text": "# ls -l output example:\n# -rwxr-xr--  1 alice  staff  1024 Jan 1 12:00 script.sh\n#  ↑↑↑ ↑↑↑ ↑↑↑\n#  │   │   └── Others: r-- (4) = read only\n#  │   └────── Group:  r-x (5) = read + execute\n#  └────────── User:   rwx (7) = read + write + execute"},
            {"type": "heading", "text": "Octal (Numeric) Mode"},
            {"type": "paragraph", "text": "Each permission class is represented as a digit 0-7 (sum of r=4, w=2, x=1)."},
            {"type": "code", "text": "# 755: owner=rwx, group=r-x, others=r-x (typical for executables/dirs)\nchmod 755 my_script.sh\n\n# 644: owner=rw-, group=r--, others=r-- (typical for config files)\nchmod 644 config.conf\n\n# 600: owner=rw-, no access for anyone else (private keys!)\nchmod 600 ~/.ssh/id_ed25519\n\n# 700: owner=rwx, no access for others (private dirs)\nchmod 700 ~/.ssh"},
            {"type": "warning", "text": "SSH private keys MUST have 600 permissions. SSH will refuse to use a key that is world-readable and print \"Permissions 0644 are too open.\""},
            {"type": "heading", "text": "Symbolic Mode"},
            {"type": "paragraph", "text": "Symbolic mode uses letters: u (user/owner), g (group), o (others), a (all). Operators: + (add), - (remove), = (set exactly)."},
            {"type": "code", "text": "# Add execute permission for owner\nchmod u+x script.sh\n\n# Remove write permission from group and others\nchmod go-w sensitive.conf\n\n# Set exact permissions for all\nchmod a=r readonly.txt\n\n# Multiple changes at once\nchmod u+x,g-w,o-rwx private_script.sh"},
            {"type": "heading", "text": "Recursive Permission Changes"},
            {"type": "code", "text": "# Apply to all files in a directory tree\nchmod -R 755 /var/www/html\n\n# Better: set 755 for dirs, 644 for files separately\nfind /var/www/html -type d -exec chmod 755 {} \\;\nfind /var/www/html -type f -exec chmod 644 {} \\;"},
            {"type": "tip", "text": "Avoid chmod -R 777. Giving everyone full write and execute access is a serious security risk. Set appropriate permissions for files vs directories separately."},
            {"type": "heading", "text": "Special Permissions"},
            {"type": "code", "text": "# SUID: executable runs as file owner, not caller\nchmod u+s /usr/bin/passwd\n\n# SGID: new files in dir inherit the dir's group\nchmod g+s /shared/project/\n\n# Sticky bit: only the file owner can delete files in the dir\nchmod +t /shared/uploads/"},
        ],
    },
    {
        "name": "sed",
        "title": "sed — Stream Editor",
        "content": [
            {"type": "heading", "text": "SYNOPSIS"},
            {"type": "code", "text": "sed [OPTIONS] SCRIPT [FILE...]\nsed [OPTIONS] -e SCRIPT ... [FILE...]"},
            {"type": "heading", "text": "Description"},
            {"type": "paragraph", "text": "sed reads input line by line, applies editing commands, and writes to stdout. It never modifies files in place by default — use -i to do so. It is most commonly used for search-and-replace."},
            {"type": "heading", "text": "The Substitute Command (s)"},
            {"type": "paragraph", "text": "Syntax: s/PATTERN/REPLACEMENT/FLAGS — the most important sed command."},
            {"type": "code", "text": "# Replace first occurrence per line\nsed 's/apple/orange/' fruits.txt\n\n# Replace ALL occurrences (global flag)\nsed 's/apple/orange/g' fruits.txt\n\n# Case-insensitive replacement\nsed 's/error/WARNING/gi' app.log"},
            {"type": "heading", "text": "In-Place Editing (-i)"},
            {"type": "code", "text": "# Modify file directly\nsed -i 's/old/new/g' config.conf\n\n# Modify with backup (safer)\nsed -i.bak 's/old/new/g' config.conf\n# Creates config.conf.bak as backup\n\n# Edit multiple files at once\nsed -i 's/old_hostname/new_hostname/g' /etc/hosts /etc/hostname"},
            {"type": "warning", "text": "sed -i modifies files in place with no undo. Always test your command without -i first, or use -i.bak to create a backup."},
            {"type": "heading", "text": "Deleting Lines"},
            {"type": "code", "text": "# Delete lines matching a pattern\nsed '/^#/d' config.conf         # delete comment lines\nsed '/^$/d' file.txt            # delete blank lines\nsed '/DEBUG/d' app.log          # delete debug log entries"},
            {"type": "heading", "text": "Addressing (Line Ranges)"},
            {"type": "code", "text": "# Substitute only on line 5\nsed '5s/old/new/' file.txt\n\n# Substitute on lines 5-10\nsed '5,10s/old/new/' file.txt\n\n# Delete lines 3 through 7\nsed '3,7d' file.txt\n\n# Print only matching lines (like grep)\nsed -n '/ERROR/p' app.log\n\n# Print lines 10-20\nsed -n '10,20p' large_file.txt"},
            {"type": "tip", "text": "The delimiter / can be replaced with any character. This is useful when your pattern contains slashes: sed 's|/old/path|/new/path|g' file.txt"},
            {"type": "heading", "text": "Capture Groups and Back-references"},
            {"type": "code", "text": "# Swap two words (ERE with -E for cleaner syntax)\n# Input:  \"John Smith\"\n# Output: \"Smith, John\"\nsed -E 's/(\\w+) (\\w+)/\\2, \\1/' names.txt"},
        ],
    },
    {
        "name": "git",
        "title": "git — Version Control Complete Guide",
        "content": [
            {"type": "heading", "text": "SYNOPSIS"},
            {"type": "code", "text": "git [--version] [--help] COMMAND [ARGS]"},
            {"type": "heading", "text": "Description"},
            {"type": "paragraph", "text": "Git is a distributed version control system. Every developer's working copy is a full repository with complete history and full version tracking, not dependent on network access or a central server."},
            {"type": "heading", "text": "1. Configuration (First-Time Setup)"},
            {"type": "code", "text": "# Set your identity (required for commits)\ngit config --global user.name \"Alice Smith\"\ngit config --global user.email \"alice@example.com\"\n\n# Set default editor for commit messages\ngit config --global core.editor vim\n\n# Set default branch name\ngit config --global init.defaultBranch main\n\n# View all settings\ngit config --list"},
            {"type": "heading", "text": "2. Starting a Repository"},
            {"type": "code", "text": "# Initialize a new repo in the current directory\ngit init\n\n# Clone an existing repo\ngit clone https://github.com/user/repo.git\n\n# Clone into a specific directory\ngit clone https://github.com/user/repo.git my_project"},
            {"type": "heading", "text": "3. The Basic Workflow"},
            {"type": "code", "text": "# Check status of working directory\ngit status\n\n# Stage specific files\ngit add file.txt\ngit add src/     # add entire directory\ngit add -p       # interactively stage hunks (very useful!)\n\n# Commit staged changes\ngit commit -m \"Add user authentication\"\n\n# Stage and commit tracked files in one step\ngit commit -am \"Fix typo in README\""},
            {"type": "heading", "text": "4. Branching and Merging"},
            {"type": "code", "text": "# Create and switch to a new branch\ngit switch -c feature/login\n\n# List all branches\ngit branch -a\n\n# Switch branches\ngit switch main\n\n# Merge a branch into current branch\ngit merge feature/login\n\n# Delete a merged branch\ngit branch -d feature/login"},
            {"type": "heading", "text": "5. Remote Repositories"},
            {"type": "code", "text": "# List remotes\ngit remote -v\n\n# Fetch changes (does not merge)\ngit fetch origin\n\n# Pull (fetch + merge)\ngit pull origin main\n\n# Push a branch\ngit push origin feature/login\n\n# Push and set upstream tracking\ngit push -u origin feature/login"},
            {"type": "heading", "text": "6. Undoing Changes"},
            {"type": "code", "text": "# Discard changes in working directory (destructive!)\ngit restore file.txt\n\n# Unstage a file (keep working copy changes)\ngit restore --staged file.txt\n\n# Undo the last commit (keep changes staged)\ngit reset --soft HEAD~1\n\n# Undo last commit and discard changes (destructive!)\ngit reset --hard HEAD~1\n\n# Revert a commit (safe - creates a new commit)\ngit revert abc1234"},
            {"type": "warning", "text": "git reset --hard and git restore permanently discard changes. They cannot be undone. Always check git status before running."},
            {"type": "heading", "text": "7. Stashing"},
            {"type": "code", "text": "# Save current changes and revert to last commit\ngit stash\n\n# List all stashes\ngit stash list\n\n# Apply and remove from stash list\ngit stash pop\n\n# Stash with a description\ngit stash push -m \"WIP: half-done login form\""},
            {"type": "heading", "text": "8. Useful Shortcuts"},
            {"type": "code", "text": "# View commit history (graph view)\ngit log --oneline --graph --all\n\n# Search commit messages\ngit log --grep=\"fix\"\n\n# Show what changed in a commit\ngit show abc1234\n\n# Find which commit introduced a bug\ngit bisect start\ngit bisect bad        # current commit is broken\ngit bisect good v1.2  # this tag was working"},
        ],
    },
    {
        "name": "rsync",
        "title": "rsync — Fast, Versatile File Synchronizer",
        "content": [
            {"type": "heading", "text": "SYNOPSIS"},
            {"type": "code", "text": "rsync [OPTIONS] SOURCE DESTINATION"},
            {"type": "heading", "text": "Description"},
            {"type": "paragraph", "text": "rsync synchronizes files and directories between two locations. Its key advantage is the delta-transfer algorithm: only the parts of files that have changed are transferred, making it extremely fast for incremental backups."},
            {"type": "note", "text": "rsync uses SSH by default for remote transfers. It requires rsync to be installed on both the local and remote machine."},
            {"type": "heading", "text": "The Most Important Flag: -a (Archive)"},
            {"type": "paragraph", "text": "-a is equivalent to -rlptgoD: recursive, preserve symlinks, permissions, timestamps, group, owner, device files. It is the go-to flag for backups."},
            {"type": "code", "text": "# Basic local sync\nrsync -av /source/dir/ /destination/dir/\n\n# Remote sync (from local to server)\nrsync -avz user@server:/remote/path/ /local/path/\n\n# Mirror: delete files at destination that no longer exist at source\nrsync -avz --delete /source/ user@server:/backup/"},
            {"type": "warning", "text": "The trailing slash on SOURCE matters! \"rsync -av src/ dst/\" syncs the CONTENTS of src into dst. \"rsync -av src dst/\" creates dst/src/. Always double-check."},
            {"type": "heading", "text": "Dry Run First"},
            {"type": "code", "text": "# Always test with --dry-run (-n) before a destructive sync\nrsync -avz --delete --dry-run /source/ user@server:/backup/\n\n# Combine with --itemize-changes for detail\nrsync -avz --delete -n --itemize-changes /source/ /dest/"},
            {"type": "tip", "text": "Always test rsync with --dry-run before using --delete. The --delete flag removes files at the destination that do not exist at the source."},
            {"type": "heading", "text": "Excluding Files and Directories"},
            {"type": "code", "text": "# Exclude a specific directory\nrsync -av --exclude=\".git/\" /project/ /backup/project/\n\n# Exclude multiple patterns\nrsync -av --exclude=\"*.tmp\" --exclude=\"node_modules/\" /src/ /dst/\n\n# Read exclusion patterns from a file\nrsync -av --exclude-from=\".rsyncignore\" /src/ /dst/"},
            {"type": "heading", "text": "Bandwidth and Progress"},
            {"type": "code", "text": "# Show transfer progress\nrsync -avz --progress user@server:/data/ /local/\n\n# Limit bandwidth to 5 MB/s\nrsync -avz --bwlimit=5120 /source/ user@server:/dest/\n\n# Use a specific SSH port\nrsync -avz -e \"ssh -p 2222\" /source/ user@server:/dest/"},
        ],
    },
    {
        "name": "scp",
        "title": "scp — Secure Copy over SSH",
        "content": [
            {"type": "heading", "text": "SYNOPSIS"},
            {"type": "code", "text": "scp [OPTIONS] [user@]host:]SRC [user@]host:]DST"},
            {"type": "heading", "text": "Description"},
            {"type": "paragraph", "text": "scp (Secure Copy Protocol) copies files between hosts over SSH. It uses the same authentication as SSH and is available wherever SSH is. For large or repeated transfers, rsync is generally preferred."},
            {"type": "note", "text": "Some newer Linux distributions deprecate scp in favor of sftp or rsync. scp uses an older SCP protocol that cannot resume interrupted transfers."},
            {"type": "heading", "text": "Basic Usage"},
            {"type": "code", "text": "# Copy a local file to a remote server\nscp /path/to/local/file.txt user@remote:/path/to/destination/\n\n# Copy a remote file to local machine\nscp user@remote:/var/log/syslog ~/Downloads/\n\n# Copy between two remote hosts\nscp user1@host1:/file.txt user2@host2:/destination/"},
            {"type": "heading", "text": "Common Options"},
            {"type": "code", "text": "# -r: Copy directories recursively\nscp -r /local/project/ user@server:/remote/projects/\n\n# -P: Specify non-standard SSH port (uppercase P!)\nscp -P 2222 file.txt user@server:/tmp/\n\n# -C: Enable compression\nscp -C large_file.tar user@server:/backup/\n\n# -i: Use specific SSH identity file\nscp -i ~/.ssh/id_rsa_prod deploy.sh user@prod-server:/opt/app/"},
            {"type": "tip", "text": "For multiple files or directories, use rsync instead. rsync can resume interrupted transfers, shows progress, and only copies changed files."},
        ],
    },
    {
        "name": "gzip",
        "title": "gzip — Compress and Decompress Files",
        "content": [
            {"type": "heading", "text": "SYNOPSIS"},
            {"type": "code", "text": "gzip [OPTIONS] [FILE...]"},
            {"type": "heading", "text": "Description"},
            {"type": "paragraph", "text": "gzip compresses files using the DEFLATE algorithm. By default it replaces the original file with a compressed version (adding .gz extension). To keep the original, use -k."},
            {"type": "heading", "text": "Compressing and Decompressing"},
            {"type": "code", "text": "# Compress a file (replaces original)\ngzip large_file.log\n# → creates large_file.log.gz, removes large_file.log\n\n# Compress and KEEP the original\ngzip -k large_file.log\n\n# Decompress\ngzip -d large_file.log.gz\n# or equivalently:\ngunzip large_file.log.gz\n\n# Decompress to stdout (useful with pipes)\ngunzip -c large_file.log.gz | grep \"ERROR\""},
            {"type": "heading", "text": "Compression Levels"},
            {"type": "code", "text": "# Fastest compression (level 1, largest file)\ngzip -1 file.txt\n\n# Best compression (level 9, slowest, smallest file)\ngzip -9 file.txt\n\n# Default is level 6 (good balance)"},
            {"type": "heading", "text": "Testing and Listing"},
            {"type": "code", "text": "# Test archive integrity\ngzip -t file.gz\n\n# List compression statistics\ngzip -l *.gz\n# Shows: compressed, uncompressed, ratio, name"},
            {"type": "tip", "text": "For better compression at the cost of speed, use bzip2 (-j with tar) or xz (-J with tar). For multi-core speed, use pigz (parallel gzip): pigz -k file.log"},
            {"type": "heading", "text": "Using with tar"},
            {"type": "code", "text": "# Create a gzipped tarball\ntar -czf archive.tar.gz ./directory/\n\n# Extract a gzipped tarball\ntar -xzf archive.tar.gz\n\n# Multi-threaded gzip via tar (much faster on large files)\ntar --use-compress-program=pigz -cvf archive.tar.gz ./directory/"},
        ],
    },
    {
        "name": "bash",
        "title": "Bash Scripting — From Zero to Script",
        "content": [
            {"type": "heading", "text": "Description"},
            {"type": "paragraph", "text": "A Bash script is a plain text file containing a sequence of commands executed by the Bash shell. Scripts automate repetitive tasks, sequence complex operations, and combine multiple commands into a reusable unit."},
            {"type": "heading", "text": "The Shebang Line"},
            {"type": "paragraph", "text": "Every Bash script should start with #!/bin/bash (the \"shebang\"). It tells the OS which interpreter to use when executing the script."},
            {"type": "code", "text": "#!/bin/bash\n# My first script\necho \"Hello, World!\""},
            {"type": "code", "text": "# Make the script executable, then run it\nchmod +x my_script.sh\n./my_script.sh"},
            {"type": "heading", "text": "Variables"},
            {"type": "code", "text": "# Assignment: no spaces around =\nNAME=\"Alice\"\nCOUNT=42\n\n# Use with $ prefix\necho \"Hello, $NAME!\"\necho \"Count is: ${COUNT}\"\n\n# Command substitution\nCURRENT_DATE=$(date +%Y-%m-%d)\necho \"Today is $CURRENT_DATE\""},
            {"type": "warning", "text": "Never put spaces around = in variable assignments. NAME = \"value\" will cause a \"command not found\" error."},
            {"type": "heading", "text": "Conditionals (if / elif / else)"},
            {"type": "code", "text": "#!/bin/bash\nFILE=\"/etc/hosts\"\n\nif [ -f \"$FILE\" ]; then\n    echo \"$FILE exists and is a file.\"\nelif [ -d \"$FILE\" ]; then\n    echo \"$FILE is a directory.\"\nelse\n    echo \"$FILE does not exist.\"\nfi"},
            {"type": "paragraph", "text": "Common test operators: -f (is a file), -d (is a directory), -e (exists), -z (empty string), -n (non-empty string), -eq (equal numbers), -ne (not equal), -lt (less than), -gt (greater than)."},
            {"type": "heading", "text": "Loops"},
            {"type": "code", "text": "# for loop over a list\nfor COLOR in red green blue; do\n    echo \"Color: $COLOR\"\ndone\n\n# for loop over files\nfor FILE in /etc/*.conf; do\n    echo \"Config: $FILE\"\ndone\n\n# while loop\nCOUNT=0\nwhile [ $COUNT -lt 5 ]; do\n    echo \"Count: $COUNT\"\n    COUNT=$((COUNT + 1))\ndone"},
            {"type": "heading", "text": "Functions"},
            {"type": "code", "text": "#!/bin/bash\n\ngreet() {\n    local name=\"$1\"  # $1 is the first argument\n    echo \"Hello, $name!\"\n}\n\ngreet \"Alice\"\ngreet \"Bob\""},
            {"type": "heading", "text": "Error Handling"},
            {"type": "code", "text": "#!/bin/bash\nset -e    # Exit immediately if a command fails\nset -u    # Treat unset variables as errors\nset -o pipefail  # Catch errors in pipes\n\n# Check exit code manually\nif ! cp source.txt dest.txt; then\n    echo \"ERROR: Copy failed!\" >&2\n    exit 1\nfi"},
            {"type": "tip", "text": "Add \"set -euo pipefail\" at the top of every production Bash script. It prevents scripts from silently continuing after errors."},
            {"type": "heading", "text": "A Complete Example: Backup Script"},
            {"type": "code", "text": "#!/bin/bash\nset -euo pipefail\n\nBACKUP_DIR=\"/mnt/backups\"\nSOURCE_DIR=\"/home/user/documents\"\nDATE=$(date +%Y%m%d_%H%M%S)\nARCHIVE=\"$BACKUP_DIR/docs_$DATE.tar.gz\"\n\nif [ ! -d \"$SOURCE_DIR\" ]; then\n    echo \"ERROR: Source dir not found: $SOURCE_DIR\" >&2\n    exit 1\nfi\n\nmkdir -p \"$BACKUP_DIR\"\ntar -czf \"$ARCHIVE\" \"$SOURCE_DIR\"\necho \"Backup created: $ARCHIVE ($(du -sh \"$ARCHIVE\" | cut -f1))\""},
        ],
    },
    {
        "name": "crontab",
        "title": "crontab — Schedule Recurring Tasks",
        "content": [
            {"type": "heading", "text": "SYNOPSIS"},
            {"type": "code", "text": "crontab [-l | -e | -r] [-u user]"},
            {"type": "heading", "text": "Description"},
            {"type": "paragraph", "text": "cron is a daemon that runs scheduled commands at specified times. Each user has their own crontab file. System-wide crontabs also exist under /etc/cron.d/."},
            {"type": "heading", "text": "Managing Your Crontab"},
            {"type": "code", "text": "# Edit your crontab in your default editor\ncrontab -e\n\n# List your current crontab\ncrontab -l\n\n# Remove your entire crontab (careful!)\ncrontab -r\n\n# Edit another user's crontab (as root)\ncrontab -u alice -e"},
            {"type": "heading", "text": "The Crontab Format"},
            {"type": "code", "text": "# ┌─────── minute       (0–59)\n# │ ┌───── hour         (0–23)\n# │ │ ┌─── day-of-month (1–31)\n# │ │ │ ┌─ month        (1–12)\n# │ │ │ │ ┌ day-of-week (0–6, Sunday=0 or 7)\n# │ │ │ │ │\n# * * * * *  command_to_execute"},
            {"type": "heading", "text": "Special Syntax and Examples"},
            {"type": "code", "text": "# Every minute\n* * * * * /path/to/command\n\n# Every 15 minutes\n*/15 * * * * /path/to/command\n\n# At 2:30 AM every day\n30 2 * * * /path/to/command\n\n# At midnight on the 1st of every month\n0 0 1 * * /path/to/command\n\n# Every weekday (Mon-Fri) at 9 AM\n0 9 * * 1-5 /path/to/command\n\n# Every 6 hours\n0 */6 * * * /path/to/command"},
            {"type": "heading", "text": "Special Strings"},
            {"type": "code", "text": "# Run once at system startup\n@reboot /path/to/startup_script.sh\n\n# @daily (same as 0 0 * * *)\n@daily /path/to/daily_backup.sh\n\n# @hourly, @weekly, @monthly, @yearly are also available"},
            {"type": "heading", "text": "Best Practices"},
            {"type": "code", "text": "# Always use absolute paths for commands\n0 2 * * * /usr/bin/python3 /home/user/scripts/backup.py\n\n# Redirect output to a log file\n*/5 * * * * /opt/myapp/check.sh >> /var/log/myapp-cron.log 2>&1\n\n# Suppress all output (silent cron)\n0 * * * * /opt/cleanup.sh > /dev/null 2>&1"},
            {"type": "warning", "text": "cron runs in a minimal environment — $PATH does not include /usr/local/bin by default. Use full absolute paths for all commands, or set PATH at the top of your crontab."},
            {"type": "tip", "text": "Use crontab.guru to visually verify your cron schedule expression before saving it."},
        ],
    },
    {
        "name": "ufw",
        "title": "ufw — Uncomplicated Firewall",
        "content": [
            {"type": "heading", "text": "SYNOPSIS"},
            {"type": "code", "text": "ufw [--dry-run] COMMAND [RULE]"},
            {"type": "heading", "text": "Description"},
            {"type": "paragraph", "text": "UFW (Uncomplicated Firewall) provides a simplified interface for managing iptables. It is the default firewall tool on Ubuntu/Debian systems. All ufw commands require root/sudo."},
            {"type": "heading", "text": "Initial Setup"},
            {"type": "code", "text": "# Check current status\nsudo ufw status verbose\n\n# IMPORTANT: Allow SSH before enabling\nsudo ufw allow ssh      # or: sudo ufw allow 22/tcp\n\n# Enable the firewall\nsudo ufw enable\n\n# Disable the firewall\nsudo ufw disable"},
            {"type": "warning", "text": "Always allow SSH (port 22) BEFORE enabling UFW. If you enable it first without an SSH rule, you will be locked out of the remote server permanently."},
            {"type": "heading", "text": "Allowing and Denying Traffic"},
            {"type": "code", "text": "# Allow by service name\nsudo ufw allow http\nsudo ufw allow https\n\n# Allow by port number\nsudo ufw allow 8080\nsudo ufw allow 8080/tcp\n\n# Allow a port range\nsudo ufw allow 6000:6007/tcp\n\n# Allow from a specific IP address\nsudo ufw allow from 192.168.1.100\n\n# Allow from IP to specific port\nsudo ufw allow from 192.168.1.0/24 to any port 5432\n\n# Deny a port (block attacker)\nsudo ufw deny from 203.0.113.100"},
            {"type": "heading", "text": "Viewing and Deleting Rules"},
            {"type": "code", "text": "# List rules with numbers\nsudo ufw status numbered\n\n# Delete a rule by number\nsudo ufw delete 3\n\n# Delete by rule specification\nsudo ufw delete allow 8080\n\n# Reset all rules (disables UFW)\nsudo ufw reset"},
            {"type": "heading", "text": "Application Profiles"},
            {"type": "code", "text": "# List available application profiles\nsudo ufw app list\n\n# Allow an application profile\nsudo ufw allow \"Nginx Full\"\nsudo ufw allow \"OpenSSH\""},
            {"type": "tip", "text": "Use \"Nginx Full\" to allow both port 80 and 443 with one rule. Use \"Nginx HTTP\" for port 80 only, \"Nginx HTTPS\" for 443 only."},
        ],
    },
    {
        "name": "ffmpeg",
        "title": "FFmpeg — Multimedia Processing",
        "content": [
            {"type": "heading", "text": "SYNOPSIS"},
            {"type": "code", "text": "ffmpeg [global_opts] {[input_opts] -i input_url} ... {[output_opts] output_url} ..."},
            {"type": "heading", "text": "Description"},
            {"type": "paragraph", "text": "FFmpeg is the leading multimedia framework for decoding, encoding, transcoding, muxing, demuxing, streaming, and filtering audio and video. It supports virtually every format and codec."},
            {"type": "heading", "text": "Basic Conversion"},
            {"type": "code", "text": "# Convert video format (FFmpeg infers codec from extension)\nffmpeg -i input.mov output.mp4\n\n# Convert audio format\nffmpeg -i input.flac output.mp3\n\n# Convert keeping original quality (no re-encoding)\nffmpeg -i input.mkv -c copy output.mp4"},
            {"type": "note", "text": "-c copy (stream copy) is extremely fast because it does not re-encode. Use it when you only need to change the container format."},
            {"type": "heading", "text": "Controlling Quality"},
            {"type": "code", "text": "# CRF: 0=lossless, 51=worst. 18-28 is typical for H.264.\nffmpeg -i input.mp4 -c:v libx264 -crf 23 output.mp4\n\n# H.265 (HEVC) — better quality at half the bitrate vs H.264\nffmpeg -i input.mp4 -c:v libx265 -crf 28 output.mp4"},
            {"type": "heading", "text": "Extracting and Combining Streams"},
            {"type": "code", "text": "# Extract audio only (-vn = no video)\nffmpeg -i input.mp4 -vn -c:a copy output.aac\n\n# Extract video only (-an = no audio)\nffmpeg -i input.mp4 -an -c:v copy output.mp4\n\n# Extract frames as images (1 per second)\nffmpeg -i input.mp4 -vf fps=1 frames/frame_%04d.jpg\n\n# Combine video and audio\nffmpeg -i video.mp4 -i audio.mp3 -c:v copy -c:a aac combined.mp4"},
            {"type": "heading", "text": "Trimming and Cutting"},
            {"type": "code", "text": "# Cut from 00:01:30 for 60 seconds (fast, no re-encode)\nffmpeg -ss 00:01:30 -i input.mp4 -t 60 -c copy clip.mp4\n\n# Cut from timestamp to timestamp\nffmpeg -i input.mp4 -ss 00:01:00 -to 00:02:30 -c copy clip.mp4"},
            {"type": "heading", "text": "Resizing and Scaling"},
            {"type": "code", "text": "# Scale to 1280x720\nffmpeg -i input.mp4 -vf \"scale=1280:720\" output.mp4\n\n# Scale to 720p height, keep aspect ratio\nffmpeg -i input.mp4 -vf \"scale=-1:720\" output.mp4"},
            {"type": "heading", "text": "Hardware Acceleration"},
            {"type": "code", "text": "# NVIDIA CUDA (encode)\nffmpeg -i input.mp4 -c:v h264_nvenc -preset fast output.mp4\n\n# NVIDIA with hardware decoding + encoding\nffmpeg -hwaccel cuda -i input.mp4 -c:v h264_nvenc output.mp4\n\n# Intel Quick Sync (VAAPI on Linux)\nffmpeg -hwaccel vaapi -i input.mp4 -c:v h264_vaapi output.mp4"},
            {"type": "tip", "text": "Hardware acceleration can be 5-20x faster than CPU encoding. NVIDIA users should use -c:v h264_nvenc, AMD users should try -c:v h264_amf."},
        ],
    },
    {
        "name": "ansible-playbook",
        "title": "Ansible — Infrastructure Automation",
        "content": [
            {"type": "heading", "text": "SYNOPSIS"},
            {"type": "code", "text": "ansible-playbook [OPTIONS] PLAYBOOK_FILE"},
            {"type": "heading", "text": "Description"},
            {"type": "paragraph", "text": "Ansible is an agentless automation tool. It connects to remote servers over SSH, runs tasks defined in YAML \"playbooks\", and ensures systems reach a desired state. No software needs to be installed on managed nodes — only Python and SSH access are required."},
            {"type": "heading", "text": "Anatomy of a Playbook"},
            {"type": "code", "text": "---\n- name: Configure web servers\n  hosts: webservers\n  become: true         # use sudo\n\n  vars:\n    app_port: 8080\n\n  tasks:\n    - name: Ensure nginx is installed\n      ansible.builtin.package:\n        name: nginx\n        state: present\n\n    - name: Ensure nginx is running\n      ansible.builtin.service:\n        name: nginx\n        state: started\n        enabled: true"},
            {"type": "heading", "text": "The Inventory File"},
            {"type": "code", "text": "# /etc/ansible/hosts\n\n[webservers]\nweb1.example.com\nweb2.example.com ansible_user=ubuntu\n192.168.1.10     ansible_port=2222\n\n[databases]\ndb1.example.com\n\n[all:vars]\nansible_python_interpreter=/usr/bin/python3"},
            {"type": "heading", "text": "Running Playbooks"},
            {"type": "code", "text": "# Run a playbook\nansible-playbook -i inventory.ini site.yml\n\n# Dry run (check mode -- no changes made)\nansible-playbook -i inventory.ini site.yml --check\n\n# Run only specific tasks (by tag)\nansible-playbook -i inventory.ini site.yml --tags \"nginx,config\"\n\n# Run against a specific host only\nansible-playbook -i inventory.ini site.yml --limit web1.example.com\n\n# Verbose mode\nansible-playbook -i inventory.ini site.yml -v"},
            {"type": "heading", "text": "Essential Modules"},
            {"type": "code", "text": "# Install a package (cross-distro)\n- ansible.builtin.package:\n    name: htop\n    state: present\n\n# Copy a file\n- ansible.builtin.copy:\n    src: files/nginx.conf\n    dest: /etc/nginx/nginx.conf\n    mode: \"0644\"\n    owner: root\n\n# Run a shell command\n- ansible.builtin.command:\n    cmd: /opt/app/deploy.sh\n\n# Create a user\n- ansible.builtin.user:\n    name: deploy\n    state: present\n    shell: /bin/bash\n    groups: sudo"},
            {"type": "note", "text": "Ansible tasks are idempotent — running a playbook multiple times produces the same result as running it once. The \"package: state: present\" task installs only if not already installed."},
            {"type": "tip", "text": "Always run with --check before applying a playbook to production. Check mode shows what WOULD change without making any actual changes."},
        ],
    },
    {
        "name": "lxc",
        "title": "LXC / Incus — System Containers and VMs",
        "content": [
            {"type": "heading", "text": "SYNOPSIS"},
            {"type": "code", "text": "lxc [SUBCOMMAND] [OPTIONS] [ARGS]"},
            {"type": "heading", "text": "Description"},
            {"type": "paragraph", "text": "LXC (Linux Containers) / Incus provides OS-level virtualization — lightweight containers that share the host kernel but have isolated filesystems, processes, and networks. Containers start in milliseconds and use far fewer resources than VMs."},
            {"type": "heading", "text": "Container Lifecycle"},
            {"type": "code", "text": "# Launch a container from an image\nlxc launch ubuntu:22.04 my-container\n\n# Launch a VM instead of a container\nlxc launch ubuntu:22.04 my-vm --vm\n\n# List all containers and VMs\nlxc list\n\n# Get a shell inside a container\nlxc exec my-container -- /bin/bash\n\n# Stop and delete\nlxc stop my-container\nlxc delete my-container"},
            {"type": "heading", "text": "Resource Limits"},
            {"type": "code", "text": "# Launch with resource limits\nlxc launch ubuntu:22.04 web-app \\\n    -c limits.cpu=2 \\\n    -c limits.memory=2GB\n\n# Set limits after launch\nlxc config set my-container limits.cpu 4\nlxc config set my-container limits.memory 4GB\n\n# View current config\nlxc config show my-container"},
            {"type": "heading", "text": "Networking"},
            {"type": "code", "text": "# Get container IP address\nlxc list -c n,4\n\n# Forward a host port to a container\nlxc config device add my-container myport proxy \\\n    listen=tcp:0.0.0.0:8080 connect=tcp:127.0.0.1:80"},
            {"type": "heading", "text": "Snapshots and Backups"},
            {"type": "code", "text": "# Create a snapshot\nlxc snapshot my-container snap-before-update\n\n# Restore a snapshot\nlxc restore my-container snap-before-update\n\n# Export a container to a file\nlxc export my-container /backups/my-container.tar.gz"},
            {"type": "tip", "text": "Take a snapshot before making significant changes to a container. Restoring from a snapshot is instantaneous, making it a fast \"undo\" mechanism."},
        ],
    },
    {
        "name": "ip",
        "title": "ip — Network Configuration",
        "content": [
            {"type": "heading", "text": "SYNOPSIS"},
            {"type": "code", "text": "ip [OPTIONS] OBJECT {COMMAND | help}"},
            {"type": "heading", "text": "Description"},
            {"type": "paragraph", "text": "The ip command is the modern replacement for ifconfig, route, and netstat. It manages network interfaces, addresses, routes, and more. It is part of the iproute2 package and is available on all modern Linux systems."},
            {"type": "heading", "text": "Network Interfaces (ip link)"},
            {"type": "code", "text": "# Show all network interfaces\nip link show\n\n# Bring an interface UP or DOWN\nsudo ip link set eth0 up\nsudo ip link set eth0 down\n\n# Set MAC address\nsudo ip link set eth0 address 02:11:22:33:44:55"},
            {"type": "heading", "text": "IP Addresses (ip addr)"},
            {"type": "code", "text": "# Show all IP addresses\nip addr show\nip a       # shorthand\n\n# Add an IP address to an interface\nsudo ip addr add 192.168.1.100/24 dev eth0\n\n# Remove an IP address\nsudo ip addr del 192.168.1.100/24 dev eth0"},
            {"type": "note", "text": "Changes made with ip are NOT persistent across reboots. To make them permanent, configure /etc/netplan/ (Ubuntu) or use NetworkManager (nmcli)."},
            {"type": "heading", "text": "Routing (ip route)"},
            {"type": "code", "text": "# Show routing table\nip route show\nip r       # shorthand\n\n# Show route to a specific destination\nip route get 8.8.8.8\n\n# Add a default route (gateway)\nsudo ip route add default via 192.168.1.1 dev eth0\n\n# Add a static route to a subnet\nsudo ip route add 10.0.0.0/8 via 192.168.1.1\n\n# Delete a route\nsudo ip route del 10.0.0.0/8"},
            {"type": "heading", "text": "Useful Inspection Commands"},
            {"type": "code", "text": "# Show neighbor (ARP) table\nip neigh show\n\n# Monitor network events in real time\nip monitor all\n\n# Show interface statistics (RX/TX bytes, errors)\nip -s link show eth0"},
            {"type": "tip", "text": "Use \"ip -c\" or \"ip -color\" for colorized output that makes it much easier to read. Many distros alias \"ip\" to include color automatically."},
        ],
    },
]
